# Generated by Django 5.0.1 on 2024-01-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_chat_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='message',
            new_name='message_f',
        ),
        migrations.AddField(
            model_name='chat',
            name='t',
            field=models.CharField(default=121, max_length=1000),
            preserve_default=False,
        ),
    ]
