# Generated by Django 5.0.1 on 2024-01-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_message_chat_message_f_chat_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('model', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('discription', models.CharField(max_length=1000)),
            ],
        ),
    ]
