# Generated by Django 5.0.1 on 2024-01-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_exchange_img_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify',
            name='img',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
