# Generated by Django 5.0.6 on 2024-05-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_history_premiumstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='totalAmount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='withdrawAmount',
            field=models.IntegerField(null=True),
        ),
    ]
