# Generated by Django 5.0.6 on 2024-05-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_history_totalamount_alter_history_withdrawamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='totalAmount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
