# Generated by Django 5.0.6 on 2024-05-28 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_history_totalamount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='exprectedPrice',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exchange',
            name='wallet',
            field=models.IntegerField(null=True),
        ),
    ]
