# Generated by Django 5.0.6 on 2024-05-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_exchange_exprectedprice_exchange_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='wallet',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
