# Generated by Django 5.0.6 on 2024-05-28 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_exchange_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.history'),
        ),
    ]
