# Generated by Django 5.0.6 on 2024-05-28 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_exchange_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='exchangeDate',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='exchangeRate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
