# Generated by Django 5.0.6 on 2024-05-28 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='model',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='name',
        ),
        migrations.AddField(
            model_name='cart',
            name='productName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
