# Generated by Django 5.0.6 on 2024-05-28 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_product_discription_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='history',
        ),
        migrations.AddField(
            model_name='history',
            name='Exchangeitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.exchange'),
        ),
    ]
