# Generated by Django 5.0.6 on 2024-05-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_exchange_history_history_exchangeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='isActive',
            field=models.CharField(default='waiting', max_length=1000),
        ),
    ]
