# Generated by Django 5.0.6 on 2024-05-28 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_exchange_isactive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premiumState', models.CharField(default='False', max_length=1000, null=True)),
                ('startDate', models.CharField(max_length=1000, null=True)),
                ('exchangeDate', models.CharField(max_length=1000, null=True)),
                ('exchangeRate', models.IntegerField(null=True)),
                ('endDate', models.CharField(max_length=1000, null=True)),
                ('withdrawAmount', models.IntegerField(null=True)),
                ('totalAmount', models.IntegerField(default=0, null=True)),
                ('Exchangeitem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.exchange')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
