# Generated by Django 4.1.7 on 2024-05-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_history_exchangeitem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='service',
        ),
    ]
